version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install flask flask-restful flask-sqlalchemy
  build:
    commands:
      - python3 -m unittest tests.unit.model.test_todo
      - python3 -m unittest tests.integration.model.test_todo
  pre_build:
    commands:
      - aws deploy push --region ap-northeast-1 --application-name todo-api-project --s3-location s3://todo-api-artifact-bucket/sample.zip --source ./
artifacts:
  files:
    - '**/*'
  base-directory: src
  name: sample.zip
